name: BUILD
on:
  push:
  schedule:
    - cron:  '1 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Brx86/update-db-for-repo@master
      with:
        tag: x86_64
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./*.db"
        token: ${{ secrets.GITHUB_TOKEN }}